max_width = 140
match_block_trailing_comma = true
edition = "2021"

# <nightly options>
# imports_granularity = "Module"
# ignore = []
# version = "Two"
# comment_width = 100
# error_on_line_overflow = true
# wrap_comments = true
